[package]
name = "lala"
version = "0.1.0"
edition = "2021"

[dependencies]
dace = { path = "../dace" }
dace_tests = { path = "../dace_tests" }
static_rd = { path = "../static_rd" }
static_ri = { path = "../static_ri" }